### ISSUE TITLE
ValueError: Stop argument for islice() must be None or an integer: 0 <= x <= sys.maxsize.

### ISSUE THREAD

**Issue by Jungle0430** [bangawayoo/mb-lm-watermarking#1]
After debugging, I discovered that setting ‘LIMIT_ROWS=-1’ in the script results in no data being retrieved from the dataset. Is this expected behavior?

**Comment by bangawayoo** [comment]
Hi. Can you tell me which script you are running and the full error trace?

**Comment by bangawayoo** [comment]
@Jungle0430, has the issue been solved? 
At a glance, seems like setting LIMIT_ROWS=-1 is indeed the issue.

I will change this for `sample-entrypoint.sh`.
Thank you for pointing this out.

Feel free to open the issue, if the same problem persists.
